### ISSUE TITLE
Zipalign missing file issue

### ISSUE THREAD

**Issue by GokhanArik** [appfoundry/fastlane-android-example#2]
Zipalign is giving me this error:

```
/Users/admin/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.1.3/fastlane/lib/fastlane/helper/sh_helper.rb:36:in `popen': [!] No such file or directory - zipalign (Errno::ENOENT)
	from /Users/admin/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.1.3/fastlane/lib/fastlane/helper/sh_helper.rb:36:in `sh_control_output'
	from /Users/admin/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.1.3/fastlane/lib/fastlane/helper/sh_helper.rb:10:in `sh'
	from /Users/admin/Projects/fno/fanx-android/fastlane/actions/zipalign.rb:23:in `run'
	from /Users/admin/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.1.3/fastlane/lib/fastlane/runner.rb:227:in `block (2 levels) in execute_action'
	from /Users/admin/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.1.3/fastlane/lib/fastlane/actions/actions_helper.rb:50:in `execute_action'
	from /Users/admin/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.1.3/fastlane/lib/fastlane/runner.rb:212:in `block in execute_action'
	from /Users/admin/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.1.3/fastlane/lib/fastlane/runner.rb:211:in `chdir'
	from /Users/admin/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.1.3/fastlane/lib/fastlane/runner.rb:211:in `execute_action'
	from /Users/admin/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.1.3/fastlane/lib/fastlane/runner.rb:133:in `trigger_action_by_name'
	from /Users/admin/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.1.3/fastlane/lib/fastlane/fast_file.rb:146:in `method_missing'
	from Fastfile:32:in `block in parsing_binding'
	from /Users/admin/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.1.3/fastlane/lib/fastlane/lane.rb:33:in `call'
	from /Users/admin/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.1.3/fastlane/lib/fastlane/lane.rb:33:in `call'
	from /Users/admin/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.1.3/fastlane/lib/fastlane/runner.rb:49:in `block in execute'
	from /Users/admin/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.1.3/fastlane/lib/fastlane/runner.rb:45:in `chdir'
	from /Users/admin/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.1.3/fastlane/lib/fastlane/runner.rb:45:in `execute'
	from /Users/admin/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.1.3/fastlane/lib/fastlane/lane_manager.rb:52:in `cruise_lane'
	from /Users/admin/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.1.3/fastlane/lib/fastlane/command_line_handler.rb:30:in `handle'
	from /Users/admin/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.1.3/fastlane/lib/fastlane/commands_generator.rb:96:in `block (2 levels) in run'
	from /Users/admin/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/commander-4.4.2/lib/commander/command.rb:178:in `call'
	from /Users/admin/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/commander-4.4.2/lib/commander/command.rb:178:in `call'
	from /Users/admin/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/commander-4.4.2/lib/commander/command.rb:153:in `run'
	from /Users/admin/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/commander-4.4.2/lib/commander/runner.rb:446:in `run_active_command'
	from /Users/admin/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.1.3/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:38:in `run!'
	from /Users/admin/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/commander-4.4.2/lib/commander/delegates.rb:15:in `run!'
	from /Users/admin/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.1.3/fastlane/lib/fastlane/commands_generator.rb:293:in `run'
	from /Users/admin/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.1.3/fastlane/lib/fastlane/commands_generator.rb:36:in `start'
	from /Users/admin/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.1.3/fastlane/lib/fastlane/cli_tools_distributor.rb:59:in `take_off'
	from /Users/admin/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.1.3/bin/fastlane:5:in `<top (required)>'
	from /Users/admin/.fastlane/bin/bundle/bin/fastlane:22:in `load'
	from /Users/admin/.fastlane/bin/bundle/bin/fastlane:22
```

any idea of what the problem is?

**Comment by nomisRev** [comment]
`zipalign` is not on your $PATH. And thus fastlane cannot find the zipalign command. It can be found @ $ANDROID_HOME/build-tools/25.0.1. Once you place the zipalign dir on your $PATH it should work fine.

**Comment by GokhanArik** [comment]
Thanks! Looks like Android moved it from tools.
