### ISSUE TITLE
zipalign fastlane finished with errors

### ISSUE THREAD

**Issue by mkiisoft** [appfoundry/fastlane-android-example#4]
I'm getting the following issue when using zipaling command: 

zipalign(apk_path: "#{lane_context[SharedValues::SIGNED_APK_PATH]}")

--------------------------------ERROR------------------------------------

`Found no similar issues. To create a new issue, please visit:
https://github.com/fastlane/fastlane/issues/new
Run `fastlane env` to append the fastlane environment to your issue
/usr/local/lib/ruby/gems/2.3.0/gems/fastlane-2.19.1/fastlane/lib/fastlane/helper/sh_helper.rb:36:in `popen': [!] No such file or directory - zipalign (Errno::ENOENT)
	from /usr/local/lib/ruby/gems/2.3.0/gems/fastlane-2.19.1/fastlane/lib/fastlane/helper/sh_helper.rb:36:in `sh_control_output'
	from /usr/local/lib/ruby/gems/2.3.0/gems/fastlane-2.19.1/fastlane/lib/fastlane/helper/sh_helper.rb:10:in `sh'
	from /Users/mariano/Documents/Android_Projects/AppFree/fastlane/actions/zipalign.rb:23:in `run'
	from /usr/local/lib/ruby/gems/2.3.0/gems/fastlane-2.19.1/fastlane/lib/fastlane/runner.rb:243:in `block (2 levels) in execute_action'
	from /usr/local/lib/ruby/gems/2.3.0/gems/fastlane-2.19.1/fastlane/lib/fastlane/actions/actions_helper.rb:50:in `execute_action'
	from /usr/local/lib/ruby/gems/2.3.0/gems/fastlane-2.19.1/fastlane/lib/fastlane/runner.rb:221:in `block in execute_action'
	from /usr/local/lib/ruby/gems/2.3.0/gems/fastlane-2.19.1/fastlane/lib/fastlane/runner.rb:217:in `chdir'
	from /usr/local/lib/ruby/gems/2.3.0/gems/fastlane-2.19.1/fastlane/lib/fastlane/runner.rb:217:in `execute_action'
	from /usr/local/lib/ruby/gems/2.3.0/gems/fastlane-2.19.1/fastlane/lib/fastlane/runner.rb:139:in `trigger_action_by_name'
	from /usr/local/lib/ruby/gems/2.3.0/gems/fastlane-2.19.1/fastlane/lib/fastlane/fast_file.rb:146:in `method_missing'
	from Fastfile:42:in `block in parsing_binding'
	from /usr/local/lib/ruby/gems/2.3.0/gems/fastlane-2.19.1/fastlane/lib/fastlane/lane.rb:33:in `call'
	from /usr/local/lib/ruby/gems/2.3.0/gems/fastlane-2.19.1/fastlane/lib/fastlane/runner.rb:49:in `block in execute'
	from /usr/local/lib/ruby/gems/2.3.0/gems/fastlane-2.19.1/fastlane/lib/fastlane/runner.rb:45:in `chdir'
	from /usr/local/lib/ruby/gems/2.3.0/gems/fastlane-2.19.1/fastlane/lib/fastlane/runner.rb:45:in `execute'
	from /usr/local/lib/ruby/gems/2.3.0/gems/fastlane-2.19.1/fastlane/lib/fastlane/lane_manager.rb:52:in `cruise_lane'
	from /usr/local/lib/ruby/gems/2.3.0/gems/fastlane-2.19.1/fastlane/lib/fastlane/command_line_handler.rb:30:in `handle'
	from /usr/local/lib/ruby/gems/2.3.0/gems/fastlane-2.19.1/fastlane/lib/fastlane/commands_generator.rb:105:in `block (2 levels) in run'
	from /usr/local/lib/ruby/gems/2.3.0/gems/commander-4.4.1/lib/commander/command.rb:178:in `call'
	from /usr/local/lib/ruby/gems/2.3.0/gems/commander-4.4.1/lib/commander/command.rb:153:in `run'
	from /usr/local/lib/ruby/gems/2.3.0/gems/commander-4.4.1/lib/commander/runner.rb:444:in `run_active_command'
	from /usr/local/lib/ruby/gems/2.3.0/gems/fastlane-2.19.1/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:38:in `run!'
	from /usr/local/lib/ruby/gems/2.3.0/gems/commander-4.4.1/lib/commander/delegates.rb:15:in `run!'
	from /usr/local/lib/ruby/gems/2.3.0/gems/fastlane-2.19.1/fastlane/lib/fastlane/commands_generator.rb:302:in `run'
	from /usr/local/lib/ruby/gems/2.3.0/gems/fastlane-2.19.1/fastlane/lib/fastlane/commands_generator.rb:42:in `start'
	from /usr/local/lib/ruby/gems/2.3.0/gems/fastlane-2.19.1/fastlane/lib/fastlane/cli_tools_distributor.rb:65:in `take_off'
	from /usr/local/lib/ruby/gems/2.3.0/gems/fastlane-2.19.1/bin/fastlane:15:in `<top (required)>'
	from /usr/local/bin/fastlane:22:in `load'
	from /usr/local/bin/fastlane:22:in `<main>'`

**Comment by mkiisoft** [comment]
Environment issue, if anyone have the same issue, follow this and you'll be ok:

http://stackoverflow.com/a/30912162
